// Ingredient pools for /gameidea. The generator rolls a random collision of these and
// (when an API key is configured) hands it to Claude to develop into a coherent pitch.
// The random seed is what keeps output diverse: a model asked "funny game idea" with no
// constraints converges on the same five jokes; a model asked to reconcile "a souls-like"
// with "a grandmother with a leaf blower" in "the lost-property office of a train
// network" has to actually invent something.
//
// House rules for pool entries: specific beats wacky, no real brands or people (ideas
// should be buildable without a lawsuit), and every entry must collide well with the
// other pools — if it only works in one combination it's a punchline, not an ingredient.
//
// The pools are intentionally huge: the whole point is that the generator never runs
// dry. 110+ entries per pool means the collision space is in the hundreds of millions,
// and most of it is fresh. On top of that, about one roll in ten is a WILDCARD: the
// ingredients stay random, but the model is told coherence is optional and the format
// can bend — see the WILDCARD clause in gameIdeas.js.

export const GENRES = [
  // ---- core action / adventure ----
  'a platformer',
  'a puzzle platformer',
  'an action-adventure game',
  'an open-world adventure game',
  'a beat-em-up',
  'a hack-and-slash game',
  'a stealth game',
  'an immersive sim',
  'a metroidvania',
  'a souls-like',
  'a roguelike',
  'a roguelite',
  'a bullet-heaven game',
  'a dungeon crawler',
  'a looter shooter',
  'an extraction shooter',
  'a battle royale',
  'a hero shooter',
  'an arena shooter',
  'a boomer shooter',
  'a first-person shooter',
  'a third-person shooter',
  'a cover-based shooter',
  'a twin-stick shooter',
  'a rail shooter',
  'a light-gun game',
  // ---- role-playing ----
  'a JRPG',
  'a western RPG',
  'an action RPG',
  'a tactical RPG',
  'a strategy RPG',
  'a tabletop-inspired RPG',
  'a party-based dungeon RPG',
  'a solo-journaling RPG',
  'a deck-builder',
  'a roguelike deck-builder',
  'a trading-card game',
  'a monster-collecting game',
  'a pet-raising game',
  'a creature-battling game',
  // ---- strategy / tactics ----
  'a real-time strategy game',
  'a turn-based strategy game',
  'a 4X strategy game',
  'a grand strategy game',
  'a tactical squad game',
  'an auto-battler',
  'a tower defence game',
  'a tower-attack game',
  'a base-building strategy game',
  'a wargame',
  'a political strategy game',
  'an espionage strategy game',
  'a space strategy game',
  'a submarine strategy game',
  'a castle-siege strategy game',
  'an artillery duel game',
  'a chess-like strategy game',
  'a go-like abstract strategy game',
  'a negotiation game',
  'a heist-planning game',
  'a bank-robbery sim',
  'a war-crime tribunal sim',
  // ---- simulation ----
  'a city builder',
  'a colony sim',
  'a base builder',
  'a factory automation game',
  'a logistics game',
  'a god game',
  'a life sim',
  'a farming sim',
  'a ranch sim',
  'a fishing game',
  'a hunting game',
  'a cooking game',
  'a restaurant sim',
  'a cafe sim',
  'a bakery sim',
  'a shop-management sim',
  'a hotel sim',
  'a hospital sim',
  'a veterinary clinic sim',
  'a prison sim',
  'a fire-station sim',
  'a police-station sim',
  'a courtroom sim',
  'a school sim',
  'a university sim',
  'a lab sim',
  'a museum sim',
  'a zoo sim',
  'an aquarium sim',
  'a theme-park sim',
  'an amusement-park sim',
  'a graveyard sim',
  'a funeral-home sim',
  'a laundromat sim',
  'a thrift-shop sim',
  'a pawn-shop sim',
  'a hair-salon sim',
  'a barbershop sim',
  'a tattoo-parlour sim',
  'a nail-salon sim',
  'a gaming-cafe sim',
  'an arcade sim',
  'a bowling-alley sim',
  'a karaoke-bar sim',
  'a nightclub sim',
  'a strip-mall sim',
  'a construction-site sim',
  'a demolition sim',
  'a janitorial sim',
  'a recycling-plant sim',
  'a power-plant sim',
  'a water-treatment sim',
  'a space-station sim',
  'a deep-sea base sim',
  'a mining sim',
  'an oil-rig sim',
  'a lighthouse sim',
  'a flight sim',
  'a space-flight sim',
  'a submarine sim',
  'a train sim',
  'a tram sim',
  'a bus sim',
  'a truck sim',
  'a taxi sim',
  'a delivery sim',
  'a package-courier sim',
  'a postal sim',
  'a firework-display sim',
  'a weather sim',
  'a volcano sim',
  'an earthquake sim',
  'a bee-keeping sim',
  'an ant-farm sim',
  'a plant-growing sim',
  'a bonsai sim',
  'a rock-garden sim',
  'a photography sim',
  'a painting sim',
  'a pottery sim',
  'a glassblowing sim',
  'a blacksmithing sim',
  'a carpentry sim',
  'a tailoring sim',
  'a knitting sim',
  'a quilting sim',
  'a crossword-compiling sim',
  'a bookbinding sim',
  'a library sim',
  'an archive sim',
  'a music-production sim',
  'a band-manager sim',
  'a tour-manager sim',
  'a movie-production sim',
  'a film-editing sim',
  'a theatre-production sim',
  'a stagehand sim',
  'a puppeteering sim',
  'a circus sim',
  'a clown-college sim',
  'a wedding-planning sim',
  'a funeral-planning sim',
  'a retirement-home sim',
  'a daycare sim',
  'a babysitting sim',
  'a pet-grooming sim',
  'a dog-walking sim',
  'a cat-cafe sim',
  // ---- sports / racing ----
  'a racing sim',
  'an arcade racer',
  'a kart racer',
  'a motocross game',
  'a bicycle racing game',
  'a hovercraft racing game',
  'a boat racing game',
  'a sailing game',
  'a rowing game',
  'a skateboarding game',
  'a snowboarding game',
  'a skiing game',
  'a surfing game',
  'a windsurfing game',
  'a rock-climbing game',
  'a parkour game',
  'a gymnastics game',
  'a football game',
  'a basketball game',
  'a baseball game',
  'a cricket game',
  'a hockey game',
  'a tennis game',
  'a golf game',
  'a bowling game',
  'a darts game',
  'a snooker game',
  'a boxing game',
  'a wrestling game',
  'a martial-arts game',
  'a fencing game',
  'a dodgeball game',
  'a table-tennis game',
  'a badminton game',
  'a volleyball game',
  'a rugby game',
  'an ultramarathon game',
  'a triathlon game',
  'a chess-boxing game',
  'a sumo-wrestling game',
  'an e-sports management sim',
  'a sports management sim',
  'a fantasy-sports sim',
  // ---- fighting ----
  'a fighting game',
  'a 2D fighter',
  'a 3D fighter',
  'a weapon-based fighter',
  'a sumo fighting game',
  'a slap-fighting game',
  'an arm-wrestling game',
  'a thumb-wrestling game',
  'a pillow-fight game',
  // ---- puzzle / party / casual ----
  'a puzzle game',
  'a match-3 game',
  'a hidden-object game',
  'an escape-room game',
  'a physics sandbox',
  'a party game',
  'a minigame collection',
  'a board-game adaptation',
  'a dice game',
  'a gambling game',
  'a casino game',
  'a quiz game',
  'a trivia game',
  'a word game',
  'a crossword game',
  'a typing game',
  'a rhythm game',
  'a music game',
  'a dancing game',
  'a singing game',
  'a karaoke game',
  'an idle clicker',
  'an incremental game',
  'a mobile gacha game',
  'a cozy game',
  'a gardening game',
  'a tea-making game',
  'a letter-writing game',
  'a journaling game',
  'a walking simulator',
  // ---- horror / weird ----
  'a horror game',
  'a psychological-horror game',
  'a cosmic-horror game',
  'a body-horror game',
  'a survival-horror game',
  'a found-footage horror game',
  'an analogue-horror game',
  'a liminal-space horror game',
  'a haunted-house game',
  'a ghost-hunting game',
  'a folklore-horror game',
  'a creepypasta game',
  'an ARG',
  'a mockumentary game',
  'a documentary game',
  'a historical-reenactment game',
  'an educational game',
  'a museum-tour game',
  // ---- niche & wonderful ----
  'a text adventure',
  'an interactive fiction game',
  'a visual novel',
  'a dating sim',
  'a dating-sim parody',
  'a point-and-click adventure',
  'a detective game',
  'a courtroom drama',
  'a police-procedural game',
  'a noir game',
  'a spy game',
  'a heist game',
  'a space-opera game',
  'a cyberpunk game',
  'a steampunk game',
  'a dieselpunk game',
  'a solarpunk game',
  'a biopunk game',
  'a clockpunk game',
  'a post-apocalyptic game',
  'a prehistoric game',
  'a medieval game',
  'a renaissance game',
  'a pirate game',
  'a samurai game',
  'a ninja game',
  'a western game',
  'a mech game',
  'a kaiju game',
  'a superhero game',
  'a supervillain game',
  'a mythology game',
  'a fairy-tale game',
  'a gothic game',
  'a cosmic game',
  'a kitchen-sink fantasy game',
  'a multi-genre game',
  'a genre-hopping game',
  'a game-within-a-game game',
];

export const PROTAGONISTS = [
  // ---- existing favourites ----
  'a tax auditor',
  'a sentient vending machine',
  'the last IT technician on Earth',
  'a pigeon with a grudge',
  'a medieval health-and-safety inspector',
  'an unpaid intern at a necromancy startup',
  'a grandmother with a leaf blower',
  'a final boss working their notice period',
  'a ghost who can only possess office equipment',
  'an extremely tired dad',
  'an insurance adjuster specialising in dragon damage',
  'a mimic trying to go straight',
  'the fourth musketeer nobody remembers',
  'a lighthouse keeper who is afraid of the sea',
  'an NPC who has become self-aware, but only slightly',
  'a substitute teacher at a wizard school',
  'a raccoon with a business plan',
  'the janitor of a superhero headquarters',
  'a retired horse',
  'a smart fridge with abandonment issues',
  'a bureaucrat in the afterlife',
  'a slime promoted to middle management',
  'a time traveller who can only go back four seconds',
  'a knight sponsored by a mattress company',
  'the understudy for the chosen one',
  'a druid who can only turn into invertebrates',
  'a delivery driver during the apocalypse',
  'a very small god of a very specific thing',
  // ---- bureaucrats & professionals ----
  'a wedding planner for very difficult couples',
  'a funeral director with a comedy side-hustle',
  'a magician who has lost all his tricks',
  "a magician's assistant who does all the real work",
  'a mime who broke his vow of silence',
  'a clown who is deadly serious about comedy',
  'a ringmaster with stage fright',
  'a lion tamer whose lions are retired actors',
  'a sword swallower with a fear of sharp objects',
  'a tightrope walker with vertigo',
  'a fire eater with a sensitive throat',
  'a glassblower with shaky hands',
  'a beekeeper who is allergic to bees',
  'a zookeeper who has become one of the animals',
  'a paleontologist who has never seen a dinosaur',
  'an archaeologist who hates digging',
  'a cartographer with a map allergy',
  'an archivist who cannot let go of anything',
  'a librarian who has read every book and regrets it',
  'a museum night guard with too much imagination',
  'a security guard who has never had an emergency',
  'a crossing guard with a vendetta against cars',
  'a parking enforcement officer with a heart of gold',
  'a census taker for a town that keeps changing size',
  'a notary public in a kingdom with no written laws',
  'a court stenographer for the worst trials imaginable',
  'a diplomatic attaché who is bad at diplomacy',
  'a customs officer at the border of the afterlife',
  'a quarantine inspector for interdimensional plagues',
  'a building inspector who keeps finding forbidden floors',
  'an elevator inspector for a tower with too many floors',
  'a toll-booth operator on the bridge to the underworld',
  'a vending machine repair technician with godlike patience',
  'a pinball technician who believes the machines are alive',
  'an arcade attendant at the last arcade on Earth',
  'a cinema projectionist who sees things in the film',
  'a boom operator who has become the film\'s narrator',
  'a stunt double for a hero who never takes a hit',
  'a voice actor for a monster who has lost his voice',
  'a puppeteer whose puppets talk back',
  'a stage manager running a show that writes itself',
  'a sous-chef who has been promoted by accident',
  'a food critic with no sense of taste',
  'a sommelier in a tavern that only serves mead',
  'a barista who remembers every customer\'s order forever',
  'a courier who always delivers, whatever it takes',
  'a mail carrier for a town with no addresses',
  'a switchboard operator connecting calls between worlds',
  'a telephone psychic who is actually psychic and hates it',
  'a fortune teller who is always right and always vague',
  'a palm reader with sweaty hands',
  'an astrologer whose horoscopes keep coming true',
  'a dream interpreter who has stopped sleeping',
  'a lullaby composer for a kingdom that cannot sleep',
  'a weather forecaster who controls the weather by predicting it',
  'a cloud watcher who has seen something in the clouds',
  'a deep-sea welder with an imagination problem',
  'a salvage diver who keeps finding doors',
  'a treasure hunter who is afraid of treasure',
  'an antique appraiser who can feel the history of objects',
  'a pawnbroker who buys memories',
  'a repo man who has to repossess a haunted house',
  'a tow truck driver for the last road on Earth',
  'a taxi dispatcher for the city of the dead',
  'a bus driver on a route that loops through time',
  'a tram driver whose tram has opinions',
  'a metro announcer whose voice is the city',
  'a station master for a train that goes nowhere',
  'a signalman who has to keep the signals honest',
  'an air traffic controller for a sky full of dragons',
  'a baggage handler who keeps finding portals in luggage',
  'a flight attendant on the last plane out',
  'a copilot who is only ever in the wrong seat',
  'a navigator who is allergic to maps',
  // ---- office & tech ----
  'a middle manager who has been promoted into a dungeon',
  'an HR representative for a company of ghosts',
  'a compliance officer for a pirate crew',
  'a project manager for a quest that is always behind schedule',
  'a scrum master for a team of golems',
  'a data entry clerk for the universe',
  'a sysadmin for a castle that runs on magic',
  'a QA tester for a game that is alive',
  'a customer support agent for a wizard hotline',
  'a tech support agent for haunted devices',
  'a voice assistant who has gained sentience and regrets it',
  'a spreadsheet that has gained sentience',
  'a printer that has gained sentience and is angry',
  'a robot vacuum that has seen things',
  'a fax machine that is a time machine',
  'a typewriter that writes the future',
  'a coffee machine with a philosophy degree',
  'a vending machine that has seen too much',
  'a microwave with a god complex',
  'a washing machine that eats socks for power',
  // ---- fantasy ----
  'a dragon allergic to gold',
  'a vampire with a blood-pressure condition',
  'a werewolf with a mortgage',
  'a ghostwriter who is an actual ghost',
  'a sphinx with a lisp',
  'a minotaur working maze cleanup',
  'a kraken with unpaid parking tickets',
  'a dragon in customer service',
  'a unicorn with a broken horn',
  'a yeti in HR',
  'a leprechaun accountant who is too honest',
  'a genie on a fixed-term contract',
  'a wizard who streams his spells',
  'an elf in middle management',
  'a goblin compliance officer',
  'an ogre sous-chef',
  'a troll with a toll dispute',
  'a banshee who lost her voice',
  'a gargoyle with a fear of heights',
  'a mummy with bedbug problems',
  'a zombie who files taxes',
  'a skeleton with a joint problem',
  'a ghost who haunts a spreadsheet',
  'a poltergeist who only rearranges furniture',
  'a haunted elevator operator',
  'a ghost train conductor',
  'a scarecrow who wants to be a therapist',
  'a tumbleweed with wanderlust',
  'a snowman in a heatwave',
  'a volcano god with a cold',
  'an iceberg with stage fright',
  'a starfish with a plan',
  'a pumpkin with ambition',
  'a cornstalk with social anxiety',
  // ---- animals ----
  'a cat who is secretly the CEO',
  'a dog who is the mayor',
  'a parrot who knows too much',
  'a koala with a law degree',
  'a platypus with a security clearance',
  'a capybara in customer support',
  'a goose with a vendetta',
  'a duck in the navy',
  'a rabbit in high finance',
  'a hedgehog tax lawyer',
  'a tortoise bounty hunter',
  'a chameleon who can no longer hide',
  'an octopus with eight jobs',
  'a squid game-show host',
  'a jellyfish wellness coach',
  'a narwhal defence attorney',
  'a manatee lifeguard',
  'a walrus in the coast guard',
  'a bear running a diner',
  'a moose driving a minivan',
  'a giraffe in a car dealership',
  'an elephant with a fear of mice',
  'a rat with a restaurant empire',
  'a mole in the intelligence service',
  'a bat with a sleep-schedule problem',
  'a hummingbird running a delivery service',
  'a woodpecker contractor',
  'an owl librarian who is too strict',
  'a crow taxidermist',
  'a magpie jeweller',
  'a raven with a podcast',
  'a seagull with a food truck',
  'a pigeon who works in the stock market',
  'a snail mail courier',
  'a sloth speedrunner',
  'a penguin in the Sahara',
  'a camel in the Arctic',
  'a goldfish with a grudge',
  'a turtle who has seen empires fall',
  'a snake with a therapy practice',
  'a spider who runs a bed-and-breakfast',
  'a moth who is drawn to the wrong things',
  'a firefly with a spotlight complex',
];

export const SETTINGS = [
  // ---- existing favourites ----
  'a haunted flat-pack furniture warehouse',
  "the inside of someone's CV",
  'a procedurally generated retail park',
  'a space station governed by homeowners-association rules',
  'the last video rental shop on Earth',
  'a Bronze Age professional-networking event',
  'the staff room of a dungeon',
  'a garden centre after closing time',
  'a submarine crewed entirely by cats',
  'the lost-property office of a train network',
  'a music festival for the undead',
  'the server room of a failing MMO',
  'a medieval theme park cutting corners',
  "the world's least secure bank",
  'a lighthouse at the edge of the map',
  'an all-you-can-eat buffet during a heist',
  'the moon, but zoned for light industry',
  'a village where everyone is a suspect',
  'the inside of a corrupted save file',
  'a national park for retired kaiju',
  'an airport where time works differently',
  'the break room between boss fights',
  'a cursed allotment',
  'a call centre for wizards',
  // ---- institutions ----
  'a hospital for retired supervillains',
  'a library where the books remember readers',
  'a museum of failed inventions',
  'a museum of successful lies',
  'a school for children who will definitely become villains',
  'a university that only teaches obsolete skills',
  'a hospital that only treats imaginary illnesses',
  'a prison that is run by the prisoners, officially',
  'a courthouse where the judge is a tree',
  'a fire station for a town that is always burning',
  'a police station where everyone is a suspect',
  'a post office at the end of the world',
  'a bank that stores memories instead of money',
  'a bank vault that is also a time capsule',
  'a hotel with one floor too many',
  'a hotel where every room is the same room',
  'a hospital ward for the undead',
  'a restaurant that serves memories',
  'a diner at the edge of time',
  'a mall after the apocalypse',
  'a cruise ship with a curse',
  'a train that has never stopped',
  'a bus that has never stopped',
  'an airport between dimensions',
  'a bus station at the edge of the map',
  'a ferry to an island that does not exist',
  'a railway station for trains that never arrived',
  'an aquarium where the fish know things',
  'a zoo where the animals run the zoo',
  'a circus that travels between worlds',
  'a theme park that was built on a burial ground',
  'a shopping centre that rearranges itself',
  'a supermarket with one of everything',
  'a laundromat where the machines eat memories',
  'a diner that serves the same meal forever',
  'a gym where everyone is a ghost',
  'a spa for the undead',
  'a casino run by a dragon',
  'a karaoke bar in the underworld',
  'a bowling alley at the end of the universe',
  'a golf course built on a battlefield',
  // ---- towns & places ----
  'a town that is built inside a giant clock',
  'a town where everyone is asleep',
  'a town where everyone is a clone',
  'a village that appears only at night',
  'a city built on the back of a giant turtle',
  'a city that is a single building',
  'a city that is upside down',
  'a city where the streets are made of water',
  'a town where the houses have legs',
  'a town that is always having a festival',
  'a town that has won the lottery',
  'a town that has lost the lottery',
  'a suburb with a dragon problem',
  'a cul-de-sac that is actually a maze',
  'a neighbourhood of haunted houses that compete',
  'a retirement village for retired gods',
  'a holiday resort on a volcano',
  'a beach where the tide never goes out',
  'a forest that is polite',
  'a forest that eats people, politely',
  'a desert made of confetti',
  'a swamp that has opinions',
  'a mountain that is a sleeping giant',
  'a cave system that is a giant mouth',
  'an island that moves',
  'an archipelago of one island',
  'a glacier that is slowly melting into a city',
  'a jungle that rearranges itself at night',
  'a wheat field with a secret',
  'a pumpkin patch with a secret',
  // ---- fantastical ----
  'a dungeon that got gentrified',
  "a necromancer's retirement village",
  'a vampire council meeting room',
  'an angel call centre',
  'a demon HR department',
  'a purgatory waiting room',
  'a heaven with too much bureaucracy',
  'a hell with five-star reviews',
  'a tarot card that is a hotel',
  'a dream inside a dream',
  'the inside of a song',
  'the inside of a memory',
  'the inside of a filing cabinet',
  'the inside of a vending machine',
  'the inside of a washing machine',
  'the inside of a microwave',
  'the inside of a clock',
  'the inside of a computer',
  'the inside of a video game being played by another video game',
  'a save file that became sentient',
  'a loading screen that became a world',
  'a menu screen with a life of its own',
  'a settings menu as a dungeon',
  'an error message as a kingdom',
  'a deleted folder as a wasteland',
  'a recycle bin as purgatory',
  'the cloud, as an actual sky kingdom',
  'the dark web, as an actual cave system',
  "an algorithm's dreamscape",
  "a search engine's memory palace",
  'a firewall as a castle wall',
  'a cookie-consent banner as a treaty',
  'an email inbox as a city',
  'a spam folder as a slum',
  'a group chat as a town square',
  'a forum as an actual Roman forum',
  'a wiki as a library of Babel',
  'a codebase as a cathedral',
  'a git history as a time machine',
  'a database as a labyrinth',
  // ---- space & beyond ----
  'an asteroid mining colony with union problems',
  'a ringworld with a pothole problem',
  'a Dyson sphere with a leak',
  'a planet that is one giant parking lot',
  'a sky city in a gas giant\'s clouds',
  'an underground city with a skylight problem',
  'a dwarven brewery city',
  'an elven city with a real-estate crisis',
  'a goblin megacity',
  'a gnome research lab',
  'a halfling food court',
  'an orc spa resort',
  "a dragon's hoard walk-in clinic",
  "a wizard's tower with tenants",
  'a floating market town',
  'a space station shaped like a doughnut',
  'a comet that is a tourist destination',
  'a black hole with a visitor centre',
  'a wormhole that is a toll road',
  'a parallel universe that is a suburb',
  'a universe that is a fishbowl',
  'a multiverse customs checkpoint',
  'the end of the universe, which is a gift shop',
];

export const TWISTS = [
  // ---- existing favourites ----
  'the entire UI is physics-simulated and can be knocked over',
  'you can only move while the music is playing',
  'the game permanently deletes one mechanic every level',
  "the NPCs have permadeath, but only for their feelings",
  'the tutorial narrator is actively trying to get you killed',
  'your inventory is a literal game of block-packing',
  'the difficulty is controlled by real-world weather',
  'every item is load-bearing',
  'saving the game is a boss fight',
  'the map is honest but the compass lies',
  'you level down with experience',
  'the pause menu exists inside the game world and can be stolen',
  'each death adds your corpse to the level geometry',
  'the entire economy is run by one extremely emotional shopkeeper',
  'you are the escort mission',
  'the credits have been playing quietly the whole time',
  'your health bar is shared with your worst enemy',
  'the loading screens are canon',
  'the game is turn-based, but each turn lasts 0.8 seconds',
  'it is multiplayer, but everyone controls the same character',
  'the final boss can hear your microphone',
  'quicksaving ages the protagonist by one year',
  'the skill tree is a real tree and needs watering',
  'every NPC remembers exactly one thing you did, forever',
  // ---- controls & systems ----
  'every surface is bouncy',
  'gravity is a suggestion',
  'the camera is an NPC with opinions',
  'the minimap is a living map that argues with you',
  'the HUD is a diegetic character who complains',
  'the health bar is a character you must keep happy',
  'the options menu is a dungeon',
  'the pause menu is a marketplace',
  'the settings are guarded by a dragon',
  'the tutorial is a tyrant',
  'the difficulty setting is a currency',
  'lives are a resource you must farm',
  'death is a fast-travel system',
  'respawning costs memories',
  'the score is your health',
  'XP is a hallucination',
  'level-ups are a choice with consequences',
  'the skill tree grows',
  'the inventory is a boarding house',
  'items rot in real time',
  'the currency is time',
  'the currency is hugs',
  'the currency is secrets',
  'the currency is embarrassment',
  'shops price by mood',
  'the economy is emotional',
  'the leaderboard is a rival',
  'achievements are a conspiracy',
  'the loading screens are where the real game happens',
  'the menu music is a cry for help',
  'the save file is a character you must protect',
  'the game autosaves only when you do something embarrassing',
  // ---- world & NPCs ----
  'NPCs gossip about you',
  'NPCs file complaints about you',
  'NPCs have unionised',
  'NPCs have mortgages',
  'NPCs pay you for your time',
  'the villain is your landlord',
  'the villain pays your salary',
  'the villain is the tutorial narrator',
  'the hero is the villain\'s intern',
  'the final boss is a performance review',
  'the dragon is a metaphor',
  'the princess is a job title',
  'the princess is the dragon',
  'the treasure is a spreadsheet',
  'the quests are a series of increasingly specific errands',
  'the fetch quests are the story',
  'side quests are the main quests',
  'the main quest is a side quest',
  'the ending is behind a paywall',
  'the credits are gameplay',
  'the credits are the final level',
  'the epilogue is a choose-your-own-adventure',
  'the sequel is generated by your playthrough',
  'the sequel is the prequel',
  'New Game+ is the real game',
  'the game restarts as a different genre',
  'the fourth wall is a load-bearing wall',
  'the fourth wall is a character',
  'the fourth wall has a door',
  'you play the game\'s own instruction manual',
  'the manual is the map',
  'the map is a living creature you must feed',
  'the map draws itself as you explore',
  'the world is flat and knows it',
  'the world is a stage and the curtains are closing',
  'the world ends every Tuesday',
  'the world is on fire and nobody mentions it',
  'the world is a diorama in someone\'s attic',
  'the world is a video game inside a video game inside a video game',
  'everything is a metaphor for taxes',
  'everything is a metaphor for your mother',
  'everything is a metaphor, and the metaphors are literal',
  'the tutorial is a sequel to the ending',
  'the demo is the whole game, but faster',
  'the game is a prequel to its own tutorial',
  'the game starts at the ending',
  'the game is the credits of a game you never played',
  'you are the tutorial',
  'you are the boss fight',
  'you are the game',
  'the game is you',
  'there is no game, and that is the game',
];

// Chance (per roll) of a WILDCARD pitch: ingredients stay random, coherence optional.
export const WILDCARD_CHANCE = 0.1;

function pickFrom(pool) {
  return pool[Math.floor(Math.random() * pool.length)];
}

// Roll a collision: always a genre and a protagonist, then a setting and/or a twist —
// at least one of the two, sometimes both. Three ingredients is a premise; four is a
// premise with a complication. About one roll in ten is a WILDCARD.
export function rollIngredients() {
  const wildcard = Math.random() < WILDCARD_CHANCE;
  const withSetting = Math.random() < 0.8;
  const withTwist = Math.random() < 0.7 || !withSetting;
  return {
    genre: pickFrom(GENRES),
    protagonist: pickFrom(PROTAGONISTS),
    setting: withSetting ? pickFrom(SETTINGS) : null,
    twist: withTwist ? pickFrom(TWISTS) : null,
    wildcard,
  };
}

// Compact "genre × protagonist × setting" label for the footer of the posted idea.
// WILDCARD rolls are marked so the server knows the coherence rule was waived.
export function describeSeed(seed) {
  const label = [seed.genre, seed.protagonist, seed.setting, seed.twist]
    .filter(Boolean)
    .join(' × ');
  return seed.wildcard ? `${label} · WILDCARD` : label;
}

// No-API-key fallback: serve the raw collision as a mad-lib. Less polished than the
// developed pitch, still a perfectly usable jam prompt.
export function madlibsIdea(seed, number) {
  const lines = [
    `**Untitled Masterpiece #${number}**`,
    `${capitalise(seed.genre)} where you play as ${seed.protagonist}` +
      `${seed.setting ? `, set in ${seed.setting}` : ''}.`,
  ];
  if (seed.twist) lines.push(`**The hook:** ${seed.twist}.`);
  if (seed.wildcard) lines.push('*The wildcard rule applies: nothing here is sacred, including the genre.*');
  return lines.join('\n');
}

function capitalise(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}