import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createImageJobStore } from '../src/services/gameIdeaImageJobs.js';
import { readImageConfig } from '../src/lib/gameIdeaScreenshot.js';
const emulator = Boolean(process.env.FIRESTORE_EMULATOR_HOST);
if (process.env.REQUIRE_FIRESTORE_EMULATOR === '1' && !emulator) throw new Error('Firestore emulator is required');

test('real Firestore: competing claims, render slots, duplicates, corrupt counters and UTC rollover', { skip: !emulator }, async t => {
  const { initializeApp, deleteApp } = await import('firebase-admin/app');
  const { getFirestore } = await import('firebase-admin/firestore');
  const app = initializeApp({ projectId: process.env.GCLOUD_PROJECT || 'demo-aigdbot-r2' }, `gameidea-${randomBytes(6).toString('hex')}`);
  const db = getFirestore(app);
  const base = 100000000000000000n + BigInt(`0x${randomBytes(7).toString('hex')}`);
  const jobs = Array.from({ length: 8 }, (_, i) => ({ messageId: String(base + BigInt(i)), channelId: '1553439895924510802', guildId: '1051088980176805919', idea: 'A fleet microwave game.', style: 'auto' }));
  const firstDay = '2098-09-30'; const nextDay = '2098-10-01';
  let date = new Date(`${firstDay}T23:59:59Z`);
  const stats = day => db.collection('gameIdeaImageStats').doc(day);
  const refs = jobs.map(j => db.collection('gameIdeaImageJobs').doc(j.messageId));
  await Promise.all([stats(firstDay).delete(), stats(nextDay).delete()]);
  t.after(async () => { await Promise.all([...refs.map(ref => ref.delete()), stats(firstDay).delete(), stats(nextDay).delete()]); await deleteApp(app); });
  const cfg = { ...readImageConfig(), dailyCap: 1, maxAttempts: 2 };
  const store = createImageJobStore(db, () => date);
  const claims = await Promise.all(jobs.slice(0, 4).map(j => store.claim(j, cfg)));
  assert.equal(claims.filter(x => x === 'claimed').length, 1);
  const winner = jobs[claims.indexOf('claimed')];
  assert.equal(await store.claim(winner, cfg), 'duplicate');
  const reservations = await Promise.all(Array.from({ length: 4 }, () => store.reserveRender(winner.messageId, cfg)));
  assert.equal(reservations.filter(Boolean).length, 1);
  await store.update(winner.messageId, { status: 'reviewing' });
  assert.equal(await store.reserveRender(winner.messageId, cfg), true);
  await store.update(winner.messageId, { status: 'reviewing' });
  assert.equal(await store.reserveRender(winner.messageId, cfg), false);
  assert.equal((await stats(firstDay).get()).data().renders, 2);
  date = new Date(`${nextDay}T00:00:01Z`);
  assert.equal(await store.claim(jobs[4], cfg), 'claimed');
  await stats(nextDay).update({ jobs: 'corrupt' });
  await assert.rejects(store.claim(jobs[5], cfg), { message: 'invalid_image_budget' });
});
