// Bounded best-effort queue. Firestore owns deduplication and UTC daily budgets.
// Generated bytes remain in memory for upload retries; never regenerate after an
// ambiguous provider/upload failure or automatically replay interrupted jobs.
import { REVIEW_KEYS, validStyle, validateBrief, validateReview } from '../lib/gameIdeaScreenshot.js';

const idPattern = /^[0-9]{17,20}$/;
export function validateImageJob(job) {
  if (!job || !['messageId', 'channelId', 'guildId'].every(k => typeof job[k] === 'string' && idPattern.test(job[k])) ||
      typeof job.idea !== 'string' || !job.idea.trim() || job.idea.length > 2600 ||
      (job.style !== 'auto' && !validStyle(job.style))) throw new Error('invalid_image_job');
  return job;
}

// No raw model output, prompt, API key, image bytes or Discord token enters Firestore.
export function createImageJobStore(db, now = () => new Date()) {
  const jobRef = id => db.collection('gameIdeaImageJobs').doc(id);
  const dayRef = date => db.collection('gameIdeaImageStats').doc(date.toISOString().slice(0, 10));
  const count = (value) => {
    if (value === undefined) return 0;
    if (!Number.isSafeInteger(value) || value < 0) throw new Error('invalid_image_budget');
    return value;
  };
  return {
    async claim(job, cfg) {
      validateImageJob(job);
      const at = now();
      return db.runTransaction(async tx => {
        const ref = jobRef(job.messageId);
        const existing = await tx.get(ref);
        if (existing.exists) return 'duplicate';
        const stats = dayRef(at);
        const snap = await tx.get(stats);
        const jobs = count(snap.data()?.jobs);
        if (jobs >= cfg.dailyCap) return 'capped';
        tx.set(stats, { jobs: jobs + 1 }, { merge: true });
        tx.set(ref, { status: 'directing', guildId: job.guildId, channelId: job.channelId,
          createdAt: at, updatedAt: at, attempts: 0, requestedStyle: job.style,
          imageModel: cfg.imageModel, directorModel: cfg.textModel });
        return 'claimed';
      });
    },
    async reserveRender(id, cfg) {
      const at = now();
      return db.runTransaction(async tx => {
        const ref = jobRef(id);
        const snap = await tx.get(ref);
        if (!snap.exists) return false;
        const data = snap.data();
        const attempts = count(data.attempts);
        if (!['directing', 'reviewing'].includes(data.status) || attempts >= cfg.maxAttempts) return false;
        const stats = dayRef(at);
        const statsSnap = await tx.get(stats);
        const renders = count(statsSnap.data()?.renders);
        if (renders >= cfg.dailyCap * cfg.maxAttempts) return false;
        tx.set(stats, { renders: renders + 1 }, { merge: true });
        tx.update(ref, { status: 'generating', attempts: attempts + 1, updatedAt: at });
        return true;
      });
    },
    async update(id, fields) {
      await jobRef(id).update({ ...fields, updatedAt: now() });
    },
  };
}

function safeFailureCode(error) {
  const message = error?.message;
  return typeof message === 'string' && /^(gemini_|invalid_|unsafe_|image_|delivery_)[a-z0-9_]{1,70}$/.test(message)
    ? message : 'image_job_failed';
}
function transientDeliveryError(error) {
  const status = Number(error?.status ?? error?.httpStatus);
  return status === 429 || status >= 500 && status <= 599 ||
    ['ECONNRESET', 'ETIMEDOUT', 'EAI_AGAIN', 'UND_ERR_CONNECT_TIMEOUT', 'UND_ERR_SOCKET'].includes(error?.code);
}

export function createImageJobService({ cfg, store, model, delivery, normalise,
  log = (event, fields) => console.log('[gameIdeaImages]', event, fields),
  delay = ms => new Promise(resolve => setTimeout(resolve, ms)) }) {
  const queue = [];
  const localIds = new Set();
  let running = false;
  const emit = (event, fields) => { try { log(event, fields); } catch { /* logging cannot break isolation */ } };

  async function run(job) {
    let claimed = false;
    const startedAt = Date.now();
    const elapsedMs = () => Math.max(0, Date.now() - startedAt);
    const reviewResults = [];
    const finish = async (status, extra = {}) => {
      if (claimed) await store.update(job.messageId, { status, ...extra });
      emit(status, { messageId: job.messageId, elapsedMs: elapsedMs(), ...extra });
      return { status, ...extra };
    };
    try {
      if (!await delivery.check(job)) return await finish('unavailable');
      const claim = await store.claim(job, cfg);
      if (claim !== 'claimed') return await finish(claim);
      claimed = true;
      emit('directing', { messageId: job.messageId, elapsedMs: elapsedMs() });
      const brief = validateBrief(await model.direct(job.idea, job.style, job.theme), job.style);
      if (!brief.safe) return await finish('rejected', { reason: 'unsafe_brief' });
      await store.update(job.messageId, { style: brief.style });
      let failedReview = null;
      for (let attempt = 0; attempt < cfg.maxAttempts; attempt++) {
        if (!await delivery.check(job)) return await finish('unavailable');
        if (!await store.reserveRender(job.messageId, cfg)) return await finish('capped');
        emit('generating', { messageId: job.messageId, attempt: attempt + 1, elapsedMs: elapsedMs() });
        const image = await normalise(await model.render(brief, failedReview));
        await store.update(job.messageId, { status: 'reviewing' });
        emit('reviewing', { messageId: job.messageId, attempt: attempt + 1, elapsedMs: elapsedMs() });
        const review = validateReview(await model.review(image, brief));
        // Keep only validated booleans and trusted check names, never reviewer prose,
        // prompts or image bytes. Preserve both attempts so corrections are diagnosable.
        const failedChecks = REVIEW_KEYS.filter(key => !review[key]);
        const outcome = { attempt: attempt + 1, review: { ...review }, failedChecks, elapsedMs: elapsedMs() };
        reviewResults.push(outcome);
        // Log before persistence so a Firestore failure cannot hide the verdict.
        emit('reviewed', { messageId: job.messageId, style: brief.style, ...outcome });
        await store.update(job.messageId, { reviewResults: [...reviewResults] });
        if (!review.safe) return await finish('rejected', { reason: 'unsafe_image', failedChecks });
        if (!Object.values(review).every(Boolean)) {
          failedReview = review;
          continue; // One correction at most; no raw reviewer prose enters the next prompt.
        }
        await store.update(job.messageId, { status: 'uploading' });
        let sent;
        for (let upload = 0; upload < 2; upload++) {
          if (!await delivery.check(job)) return await finish('unavailable');
          try {
            sent = await delivery.send(job, image, brief.style);
            break;
          } catch (err) {
            if (upload || !transientDeliveryError(err)) throw new Error('delivery_failed');
            await delay(1000); // Same bytes, same Discord nonce; never another image call.
          }
        }
        // A metadata failure after successful delivery must never cause another send.
        try { await store.update(job.messageId, { status: 'sent', replyMessageId: sent.id }); }
        catch { emit('image_sent_metadata_failed', { messageId: job.messageId, replyMessageId: sent.id }); }
        emit('sent', { messageId: job.messageId, replyMessageId: sent.id, style: brief.style, elapsedMs: elapsedMs() });
        return { status: 'sent', replyMessageId: sent.id };
      }
      return await finish('rejected', { reason: 'visual_checks_failed',
        failedChecks: reviewResults.at(-1)?.failedChecks ?? [] });
    } catch (error) {
      const reason = safeFailureCode(error);
      if (claimed) {
        try { await store.update(job.messageId, { status: 'failed', reason }); }
        catch { /* Keep the existing reservation: fail closed, never refund unknown spend. */ }
      }
      emit('failed', { messageId: job.messageId, reason, elapsedMs: elapsedMs() });
      return { status: 'failed', reason };
    }
  }
  async function drain() {
    if (running) return;
    running = true;
    try {
      while (queue.length) {
        const { job, resolve } = queue.shift();
        try { resolve(await run(job)); }
        finally { localIds.delete(job.messageId); }
      }
    } finally { running = false; }
  }
  return {
    enqueue(input) {
      if (!cfg.enabled || !cfg.apiKey || !cfg.dailyCap) return { status: 'disabled' };
      let job;
      try { job = { ...validateImageJob(input) }; } catch { return { status: 'invalid' }; }
      if (localIds.has(job.messageId)) return { status: 'duplicate' };
      if (localIds.size >= cfg.queueSize) return { status: 'full' };
      localIds.add(job.messageId);
      let resolve;
      const done = new Promise(r => { resolve = r; });
      queue.push({ job, resolve });
      queueMicrotask(() => { void drain(); });
      return { status: 'queued', done };
    },
  };
}
